POST https://lorenzo-simple-crud.onrender.com/product
Content-Type: application/json

{
  "name": "Long neck heineken",
  "price": 5,
  "quantity": 8
}

###

GET https://lorenzo-simple-crud.onrender.com/

###

PUT https://lorenzo-simple-crud.onrender.com/product/827165d1-dad8-4d34-ba46-db66a69715da
Content-Type: application/json

{
  "name": "editei",
  "price": 5,
  "quantity": 8
}

###

DELETE https://lorenzo-simple-crud.onrender.com/product/827165d1-dad8-4d34-ba46-db66a69715da
